branches:
  only:
  - master
  - development
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements.txt
- pip install coveralls
- cython src/*.pyx
- python setup.py develop
script:
- coverage run -m nose -I canonical_test
- python tests/canonical_test.py
after_success: coveralls
deploy:
  provider: pypi
  user: fgregg
  password:
    secure: O/EwutOV8DmlYJ7dPJ2st7nGDKEaTaA/gwx7mxzFQYYlyJ7Iu87QXwEY3gPGFOGDh6eyg2qMqtKPTJnXTnltb8ROFX61WKu3F/do1cORFPDQneOAzyzL7ID+a7RaMaeUQ1gRFDo5nJuGGW8wmC8LZUjwcrtrx2zlYcEydq1CW+A=
  on:
    tags: true
    all_branches: true
    repo: datamade/dedupe
sudo: false
