branches:
  only:
    - master
    - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
language: python
sudo: false
matrix:
  include:
  - python: 3.6
  - python: 3.5
  - python: 2.7
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - brew install python2
      - pip install virtualenv
      - python2 -m virtualenv env
      - source env/bin/activate
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - python3 -m venv env
      - source env/bin/activate
  - services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    before_install:
      - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
    install:
      - docker pull $DOCKER_IMAGE
    script:
      - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
      - pip install twine && twine upload -u datamade.wheelbuilder -p $PYPIPASSWORD wheelhouse/*
      - exit 0
  - services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    before_install:
      - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
    install:
      - docker pull $DOCKER_IMAGE
    script:
      - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
      - pip install twine && twine upload -u datamade.wheelbuilder -p $PYPIPASSWORD wheelhouse/*
      - exit 0
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - cython src/*.pyx
  - pip install -e .
script:
  - pytest tests --cov dedupe
  - python tests/canonical.py -vv
after_success:
  - pip install coveralls
  - coveralls
deploy:
  - provider: pypi
    skip_cleanup: true
    user: datamade.wheelbuilder
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    distributions: bdist_wheel
    password: $PYPIPASSWORD
  - provider: pypi
    skip_cleanup: true
    user: datamade.wheelbuilder
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    distributions: sdist
    password: $PYPIPASSWORD
env:
  global:
    - secure: T3lCe9jJUbYLB0WHgSD+utrmJSvgcXCLi+Lwugsaa2SXIX8UzL7TbwHWB1t10H4sddy0QBBwanqRptv6iZ7gN0EtIE6+BDv6FJcNZJBDp13pUoQqq1Fm3OMbEniLrc/ubV6mZyJLHh6oNJtzSWPk1wrFvByLpYskeZIm4ayw4Mc=
cache:
  directories:
    - "$HOME/.cache/"
    - .cache
