branches:
  only:
    - master

language: python
notifications:
  email: 
    on_success: change
    on_failure: always
  irc : "chat.freenode.net#dedupe"
    
  
python:
  - "2.7"
  - "2.6"
install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install --use-mirrors -r py26_requirements.txt; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install --use-mirrors -r requirements.txt; fi
  - pip install coveralls
  - python setup.py develop
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests, e.g. python setup.py test
script: 
  - coverage run -m nose -I canonical_test
  - nosetests test/canonical_test*
after_success:
    coveralls
